import { CheckCircle2, KeyRound, Network, Plus, Server, XCircle } from "lucide-react";
import { requireAdmin } from "@/lib/admin-auth";
import { getLabDashboard, getProviderStatuses } from "@/lib/llm-lab-admin";
import { DashboardLayout } from "../../components/DashboardLayout";
import { createModelAction, createProviderAction, setModelEnabledAction, setProviderEnabledAction, testProviderAction } from "../actions";

type SearchParams = Record<string, string | string[] | undefined>;
function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }

export default async function PromptLabProvidersPage({ searchParams }: { searchParams?: Promise<SearchParams> }) {
  await requireAdmin();
  const [dashboard, statusList, query] = await Promise.all([getLabDashboard(1), getProviderStatuses(), searchParams ?? Promise.resolve({} as SearchParams)]);
  const status = new Map(statusList.map((item) => [item.providerId, item.configured]));
  const error = first(query.error); const success = first(query.success);
  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-cyan-700">Prompt Lab / Infrastructure</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Provider control plane</h1><p className="mt-2 max-w-2xl text-sm text-zinc-500">Manage public connection metadata and explicit model catalogs. Secret values are resolved only from Convex environment variables.</p></div><div className="rounded-full border bg-white px-4 py-2 text-xs font-semibold text-zinc-600">{dashboard.providers.length} providers · {dashboard.models.length} models</div></header>
    {error || success ? <div className={`rounded-xl border p-3 text-sm ${error ? "border-rose-200 bg-rose-50 text-rose-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error ?? success?.replaceAll("_", " ")}</div> : null}
    <div className="grid gap-4 lg:grid-cols-3">{dashboard.providers.map((provider) => { const configured = status.get(String(provider._id)) === true; const models = dashboard.models.filter((model) => model.providerId === provider._id); return <article key={provider._id} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b bg-zinc-950 p-5 text-white"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><Server className="h-5 w-5 text-cyan-300"/></div><span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase ${configured ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" : "border-rose-400/30 bg-rose-400/10 text-rose-300"}`}>{configured ? "configured" : "missing key"}</span></div><h2 className="mt-4 font-semibold">{provider.name}</h2><p className="mt-1 font-mono text-[10px] text-zinc-500">{provider.protocol} · {provider.kind}</p></div><div className="space-y-4 p-5"><div className="space-y-2 font-mono text-[11px] text-zinc-500"><p className="truncate">{provider.baseUrl}</p><p className="flex items-center gap-2"><KeyRound className="h-3.5 w-3.5"/>{provider.apiKeyEnvVar}</p></div><div className="space-y-2">{models.map((model) => <div key={model._id} className="flex items-center justify-between rounded-xl bg-zinc-50 p-3"><div><p className="font-mono text-xs font-semibold">{model.displayName}</p><p className="mt-1 text-[10px] text-zinc-500">{model.modelId}</p></div><form action={setModelEnabledAction}><input type="hidden" name="modelId" value={model._id}/><input type="hidden" name="enabled" value={model.enabled ? "false" : "true"}/><button title={model.enabled ? "Disable model" : "Enable model"}>{model.enabled ? <CheckCircle2 className="h-5 w-5 text-emerald-500"/> : <XCircle className="h-5 w-5 text-zinc-400"/>}</button></form></div>)}</div><div className="flex gap-2"><form action={testProviderAction} className="flex-1"><input type="hidden" name="providerId" value={provider._id}/><button disabled={!configured} className="w-full rounded-xl border px-3 py-2 text-xs font-bold disabled:text-zinc-300"><Network className="mr-2 inline h-4 w-4"/>Test connection</button></form><form action={setProviderEnabledAction}><input type="hidden" name="providerId" value={provider._id}/><input type="hidden" name="enabled" value={provider.enabled ? "false" : "true"}/><button className="rounded-xl border px-3 py-2 text-xs font-bold">{provider.enabled ? "Disable" : "Enable"}</button></form></div></div></article>; })}</div>
    <div className="grid gap-6 xl:grid-cols-2"><form action={createProviderAction} className="space-y-4 rounded-2xl border bg-white p-6"><div className="flex items-center gap-3"><Plus className="h-5 w-5 text-cyan-700"/><div><h2 className="font-bold">Add OpenAI-compatible gateway</h2><p className="text-xs text-zinc-500">HTTPS public endpoints only.</p></div></div><div className="grid grid-cols-2 gap-3"><input required name="name" placeholder="Display name" className="rounded-xl border p-3 text-sm"/><input required name="key" placeholder="provider-key" className="rounded-xl border p-3 font-mono text-sm"/></div><input required name="baseUrl" placeholder="https://gateway.example.com/v1" className="w-full rounded-xl border p-3 font-mono text-sm"/><input required name="apiKeyEnvVar" placeholder="GATEWAY_API_KEY" pattern="[A-Z][A-Z0-9_]+" className="w-full rounded-xl border p-3 font-mono text-sm"/><div className="grid grid-cols-3 gap-3"><select name="kind" className="rounded-xl border p-3 text-sm"><option value="gateway">Gateway</option><option value="official">Official</option></select><select name="protocol" className="rounded-xl border p-3 text-sm"><option value="openai_compatible">OpenAI compatible</option><option value="gemini">Gemini</option></select><select name="authMode" className="rounded-xl border p-3 text-sm"><option value="bearer">Bearer</option><option value="api_key">api-key header</option></select></div><button className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">Create provider</button></form>
      <form action={createModelAction} className="space-y-4 rounded-2xl border bg-white p-6"><div className="flex items-center gap-3"><Plus className="h-5 w-5 text-cyan-700"/><div><h2 className="font-bold">Register model</h2><p className="text-xs text-zinc-500">Capabilities control allowed sampling parameters.</p></div></div><select required name="providerId" className="w-full rounded-xl border p-3 text-sm">{dashboard.providers.map((provider) => <option key={provider._id} value={provider._id}>{provider.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input required name="displayName" placeholder="Display name" className="rounded-xl border p-3 text-sm"/><input required name="modelId" placeholder="model-id" className="rounded-xl border p-3 font-mono text-sm"/></div><div className="grid grid-cols-4 gap-2"><input name="defaultTemperature" placeholder="Temp" type="number" step="0.05" className="rounded-xl border p-3 text-xs"/><input name="defaultTopP" placeholder="Top P" type="number" step="0.05" className="rounded-xl border p-3 text-xs"/><input name="defaultMaxTokens" placeholder="Default tokens" type="number" className="rounded-xl border p-3 text-xs"/><input name="maxOutputTokens" placeholder="Max tokens" type="number" className="rounded-xl border p-3 text-xs"/></div><div className="flex flex-wrap gap-4 text-xs">{[["supportsStructuredOutput","Structured output"],["supportsThinking","Thinking"],["supportsTemperature","Temperature"]].map(([name,label]) => <label key={name} className="flex items-center gap-2"><input type="checkbox" name={name} defaultChecked className="accent-cyan-700"/>{label}</label>)}</div><button className="rounded-xl bg-cyan-700 px-4 py-3 text-sm font-bold text-white">Register model</button></form></div>
  </div></DashboardLayout>;
}
